language: go

go:
  - 1.15.x
  - 1.16.x

env:
  global:
    - GO111MODULE=on

before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.3
  - go get github.com/securego/gosec/cmd/gosec

script:
  - make

after_success:
  - bash ./scripts/run-codecov
