// Author: Antoine Mercadal
// See LICENSE file for full LICENSE
// Copyright 2016 Aporeto.

package elemental

// UniqueScope is a the type used to define uniqueness.
type UniqueScope int

const (
	// LocallyUnique represents the uniqueness in a particular context.
	LocallyUnique UniqueScope = iota + 1

	// GloballyUnique represents the absolute uniqueness.
	GloballyUnique
)

// AttributeInfo represents all the metadata of an attribute.
type AttributeInfo struct {
	AllowedChars  string
	AllowedValues []string
	Autogenerated bool
	Availability  string
	Channel       string
	CreationOnly  bool
	DefaultOrder  bool
	Deprecated    bool
	Exposed       bool
	Filterable    bool
	Format        string
	MaxValue      float64
	MaxLength     uint
	MinValue      float64
	MinLength     uint
	Orderable     bool
	ReadOnly      bool
	Required      bool
	SubType       string
	Transient     bool
	Type          string
	Unique        bool
	UniqueScope   UniqueScope
}
