package elemental

import (
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

func TestAttribute_Interface(t *testing.T) {

	Convey("Given I create a new *List", t, func() {

		l := NewList()

		Convey("Then the list should implement the AttributeSpecifiable interface", func() {
			So(l, ShouldImplement, (*AttributeSpecifiable)(nil))
		})
	})
}

func TestAttribute_SpecificationForAttribute(t *testing.T) {

	Convey("Given I create a new List", t, func() {

		l := NewList()

		Convey("When I get the Attribute specification for the name", func() {

			spec := l.SpecificationForAttribute("Name")

			Convey("then it should be correct", func() {
				So(spec.AllowedChars, ShouldEqual, "")
				So(len(spec.AllowedChoices), ShouldEqual, 0)
				So(spec.Autogenerated, ShouldBeFalse)
				So(spec.Availability, ShouldBeEmpty)
				So(spec.Channel, ShouldBeEmpty)
				So(spec.CreationOnly, ShouldBeFalse)
				So(spec.DefaultOrder, ShouldBeFalse)
				So(spec.Deprecated, ShouldBeFalse)
				So(spec.Exposed, ShouldBeTrue)
				So(spec.Filterable, ShouldBeTrue)
				So(spec.ForeignKey, ShouldBeFalse)
				So(spec.Getter, ShouldBeTrue)
				So(spec.Identifier, ShouldBeFalse)
				So(spec.Index, ShouldBeFalse)
				So(spec.MaxLength, ShouldEqual, 0)
				So(spec.MaxValue, ShouldEqual, 0)
				So(spec.MinLength, ShouldEqual, 0)
				So(spec.MinValue, ShouldEqual, 0)
				So(spec.Orderable, ShouldBeTrue)
				So(spec.PrimaryKey, ShouldBeFalse)
				So(spec.ReadOnly, ShouldBeFalse)
				So(spec.Required, ShouldBeTrue)
				So(spec.Setter, ShouldBeTrue)
				So(spec.Stored, ShouldBeTrue)
				So(spec.SubType, ShouldBeEmpty)
				So(spec.Transient, ShouldBeFalse)
			})
		})
	})
}

func Test_ResetSecretAttributesValues(t *testing.T) {

	Convey("Given I have an identifiable with a secret property", t, func() {

		l := NewList()
		l.Secret = "it's a secret to everybody"

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(l)

			Convey("Then the secret should have been erased", func() {
				So(l.Secret, ShouldEqual, "")
			})
		})
	})

	Convey("Given I have some identifiables with a secret property", t, func() {

		l1 := NewList()
		l1.Secret = "it's a secret to everybody"

		l2 := NewList()
		l2.Secret = "it's a secret to everybody"

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(ListsList{l1, l2})

			Convey("Then the secret should have been erased", func() {
				So(l1.Secret, ShouldEqual, "")
				So(l2.Secret, ShouldEqual, "")
			})
		})
	})

	Convey("Given I have an sparse identifiable with a secret property", t, func() {

		val := "it's a secret to everybody"

		l := NewSparseList()
		l.Secret = &val

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(l)

			Convey("Then the secret should have been erased", func() {
				So(l.Secret, ShouldBeNil)
			})
		})
	})

	Convey("Given I have some sparse identifiables with a secret property", t, func() {

		l1 := NewSparseList()
		val1 := "it's a secret to everybody"
		l1.Secret = &val1

		l2 := NewSparseList()
		val2 := "it's a secret to everybody"
		l2.Secret = &val2

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(SparseListsList{l1, l2})

			Convey("Then the secret should have been erased", func() {
				So(l1.Secret, ShouldBeNil)
				So(l2.Secret, ShouldBeNil)
			})
		})
	})

	Convey("Given I have some random non pointer struct", t, func() {

		s := struct{}{}

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(s)

			Convey("Then it should not panic", func() {
				So(func() { ResetSecretAttributesValues(s) }, ShouldNotPanic)
			})
		})
	})

	Convey("Given I have some random pointer struct", t, func() {

		s := &struct{}{}

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(s)

			Convey("Then it should not panic", func() {
				So(func() { ResetSecretAttributesValues(s) }, ShouldNotPanic)
			})
		})
	})

	Convey("Given I have an non pointer identifiable with a secret property", t, func() {

		l := NewList()
		l.Secret = "it's a secret to everybody"

		Convey("When I call ResetSecretAttributesValues", func() {

			ResetSecretAttributesValues(*l)

			Convey("Then the secret should have been erased", func() {
				So(l.Secret, ShouldEqual, "it's a secret to everybody")
			})
		})
	})
}
