package versions

// This code is autogenerated by apolibver. Do not edit manually.

import (
	"encoding/json"
	"fmt"

	"go.uber.org/zap/zapcore"
)

// Versions of the current project.
var (
	ProjectVersion = "master"
	ProjectSha     = "edcc353e7c61c4c3775380b37e04ca8ba747d13f"
)

// Versions of the various libraries used by the project.
var ()

// Fields returns a ready to dump zap.Fields containing all the versions used.
func Fields() []zapcore.Field {

	return []zapcore.Field{}
}

// Map returns the version information as a map.
func Map() map[string]interface{} {

	return map[string]interface{}{
		"version": ProjectVersion,
		"sha":     ProjectSha[0:7],
		"libs":    map[string]string{},
	}
}

// ToString returns the string version of versions
func ToString(prefix string) string {

	buffer := fmt.Sprintf("%s%32s : %s\n", prefix, "ProjectVersion", ProjectVersion)
	buffer += fmt.Sprintf("%s%32s : %s\n", prefix, "ProjectSha", ProjectSha[0:7])
	buffer += fmt.Sprintf("%s%32s : %s\n", prefix, "Libraries", "")
	return buffer
}

// JSON returns the version as a ready to send json data.
func JSON() ([]byte, error) {

	return json.MarshalIndent(Map(), "", "    ")
}
